import type { Metadata } from "next";

export const links = {
  ownerName: "Upendra",
  ownerEmail: "upendrauniversity@gmail.com",
  github: "https://github.com/KING-UPE",
  facebook: "https://web.facebook.com/profile.php?id=61574713296803",
  linkedin: "https://www.linkedin.com/in/upendra-uddimantha-a09046283",
  instagram: "https://www.instagram.com/__crazy._.demon__",
  youtube: "https://www.youtube.com/@upendra_dasanayaka",
} as const;

export const siteConfig: Metadata = {
  title: `Upendra Dasanayaka`,
  description: `Upendra Dasanayaka - A Software Engineer with a passion for creating innovative solutions. Explore my portfolio to see my work and projects.`,
  keywords: [
    "reactjs",
    "nextjs",
    "vercel",
    "react",
    "aceternity",
    "aceternity-ui",
    "shadcn",
    "shadcn-ui",
    "radix-ui",
    "cn",
    "clsx",
    "modern-portfolio",
    "portfolio",
    "3d-portfolio",
    "animated-portfolio",
    "nextjs-portfolio",
    "react-portfolio",
    "react-three-fiber",
    "three.js",
    "animated-website",
    "framer",
    "framer-motion",
    "three",
    "react-icons",
    "lucide-react",
    "next-themes",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "eslint",
    "html",
    "css",
  ],
  authors: {
    name: links.ownerName,
    url: links.github,
  },
  icons: {
    icon: "/favicon.ico",
  },
} as const;
